channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  # - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - asttokens=2.0.5
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - colorcet=3.1.0
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  # - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.5.2
  - jpeg=9e
  # - jupyter_client=8.6.0
  # - jupyter_core=5.7.2
  - jupyter=1.1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  # - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  # - libcups=2.4.2
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  # - libgcc=14.2.0
  # - libgcc-ng=14.2.0
  # - libgfortran-ng=11.2.0
  # - libgfortran5=13.2.0
  - gfortran=11.3.0
  - libglib=2.78.4
  # - libgomp=14.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  # - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  # - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  # - mkl=2023.1.0
  # - mkl-service=2.4.0
  # - mkl_fft=1.3.11
  # - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.0
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statannotations=0.7.1
  - statsmodels=0.14.5
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - charset-normalizer==3.4.3
      - idna==3.10
      - natsort==8.4.0
      - requests==2.32.5
      - tensorly==0.9.0
      - tensorly-viz==0.1.7
      - urllib3==2.5.0
      - xarray==2025.9.1

